/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module "vue" {
  export interface GlobalComponents {
    CommonGoBack: (typeof import("./components/CommonGoBack.vue"))["default"];
    CommonLoading: (typeof import("./components/CommonLoading.vue"))["default"];
    CommonShareHint: (typeof import("./components/CommonShareHint.vue"))["default"];
    HelloWorld: (typeof import("./components/HelloWorld.vue"))["default"];
    RouterLink: (typeof import("vue-router"))["RouterLink"];
    RouterView: (typeof import("vue-router"))["RouterView"];
  }
}
